---
- name: Install the latest version of Squid
  ansible.builtin.package:
    name: squid
    state: latest
    
  
- name: Enable service Squid and ensure it is not masked
  ansible.builtin.systemd:
    name: squid
    enabled: yes
    masked: no
    state: started