- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add sudoers users to wheel group
  user:
    name=jim
    groups=wheel
    append=yes
    state=present
    createhome=yes

- name: Set up authorized keys for the thor user
  authorized_key: user=jim key="{{item}}"
  with_file:
    - /home/jim/.ssh/id_rsa.pub
