---
- name: Install the latest version of Cronie
  ansible.builtin.package:
    name: cronie
    state: latest
    
  
- name: Enable service Cronie and ensure it is not masked
  ansible.builtin.systemd:
    name: cron
    enabled: yes
    masked: no
  notify: start cron