---
- name: Install the latest version of Cronie
  ansible.builtin.package:
    name: cronie
    state: latest
    
  
- name: Enable service crond and ensure it is not masked
  ansible.builtin.systemd:
    name: crond
    enabled: yes
    masked: no
    state: started

